//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bomSampleApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagory
    {
        public Catagory()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int CatagoryId { get; set; }
        public string CatagoryName { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
