//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string WifeFirstName { get; set; }
        public string MaidenName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public string Infertility { get; set; }
        public string HighReskPregnancy { get; set; }
        public string MedicalFertilityPreservation { get; set; }
        public string GeneticsPediatric { get; set; }
        public string Insurance { get; set; }
        public string Adoption { get; set; }
        public Nullable<int> ApplicationStatusID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Denied { get; set; }
    
        public virtual ApplicationStatu ApplicationStatu { get; set; }
        public virtual Catagory Catagory { get; set; }
    }
}
