//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendVia
    {
        public SendVia()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int SendViaID { get; set; }
        public string SendViaName { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
